# Create a cache on the KVM host of selected apiSiteFiles data
# so 1. we have a known-good copy before starting building the VM
# and 2. so we can estimate the size of the `data` virtual disk image
# that will ultimately receive the files.
#

- name: "set_fact buildnumber"
  set_fact: buildnumber="{{ dashboard.wdk.buildnumber }}"

- name: "set_fact product"
  set_fact: product="{{ dashboard.wdk.modelname }}"

- set_fact: cache_dir="{{ staging_dir }}/{{ product }}/apiSiteFilesMirror/{{ product }}"

- name: synchronize apiSiteFilesMirror to local cache at {{ cache_dir }}
  synchronize:
    mode: pull
    src: "/var/www/Common/apiSiteFilesMirror/webServices/{{ product }}/build-{{ buildnumber }}"
    dest: "{{ cache_dir }}"
    delete: yes
    verify_host: no
    partial: no
    rsync_opts:
      - "--exclude-from=oprdatafiles.ws.rsync.exclude"
    # TODO: put excludes in an ansible vars file
