# Create a cache on the KVM host of selected apiSiteFiles data
# so 1. we have a known-good copy before starting building the VM
# and 2. so we can estimate the size of the `data` virtual disk image
# that will ultimately receive the files.
#

- name: "set_fact buildnumber: {{ ebrc.wdk.buildnumber }}"
  set_fact: buildnumber="{{ ebrc.wdk.buildnumber }}"

- name: "set_fact product: {{ ebrc.wdk.product }}"
  set_fact: product="{{ ebrc.wdk.product }}"

- name: "set_fact cache_dir: {{ packer_staging_dir }}/{{ product }}/apiSiteFilesMirror/{{ product }}"
  set_fact: cache_dir="{{ packer_staging_dir }}/{{ product }}/apiSiteFilesMirror/{{ product }}"

- name: synchronize apiSiteFilesMirror to local cache at {{ cache_dir }}
  synchronize:
    mode: pull
    src: "/var/www/Common/apiSiteFilesMirror/webServices/{{ product }}/build-{{ buildnumber }}"
    dest: "{{ cache_dir }}"
    dest_port: 2112
    delete: yes
    verify_host: no
    partial: no
    rsync_opts:
      - "--exclude-from=oprdatafiles.ws.rsync.exclude"
    # TODO: put excludes in an ansible vars file
