- set_fact: buildnumber="{{ ebrc.wdk.buildnumber }}"
- set_fact: product="{{ ebrc.wdk.modelname }}"

- name: calculate size of cached apiSiteFilesMirror
  shell: "du -s -b --apparent-size {{ packer_staging_dir }}/{{ product }}/apiSiteFilesMirror/{{ product }}  | cut -f -1"
  register: asfDiskUsageBytes

- set_fact: dataImageSizeGB="{{ (( (asfDiskUsageBytes.stdout.0|int * 1.10) / 1024**3 ) +5) | round(1, 'ceil') }}G"
- set_fact: data_img="{{ packer_staging_dir }}/{{ product }}/{{ product }}_{{ buildnumber }}.data.img"
- file: path="{{ data_img }}" state=absent
  when: do_full_rebuild|bool == True
- name: "qemu-img create {{ dataImageSizeGB }} data image"
  command: "qemu-img create -f qcow2 {{ data_img }} {{ dataImageSizeGB }}"
  args:
    creates: "{{ data_img }}"
